from decimal import Decimal
from typing import AsyncIterator, Protocol
from src.core.entities import Asset, Exchange, Coin, Ticker


class IExchange(Protocol):
    async def buy(self, asset: "Ticker"): ...
    async def sell(self, asset: "Ticker"): ...
    async def transfer(self, asset: "Asset", destination: "Exchange"): ...
    def subscribe_balance(self, coins: set["Coin"]) -> AsyncIterator["Asset"]: ...
    def subscribe_price(self, coins: set["Coin"]) -> AsyncIterator["Ticker"]: ...
    async def launch(self): ...
    async def stop(self): ...
    async def get_withdrawal_fee(self, coin: "Coin") -> Decimal:...
    async def get_available_coins(self) -> list[Coin]:...
    async def get_initial_price(self, coin: Coin) -> Decimal:...
    def get_usdt(self) -> "Coin": ...
    async def get_trading_fee(self, base: "Coin", quote: "Coin") -> Decimal:...