from __future__ import annotations

import asyncio
from decimal import Decimal
from typing import Protocol, AsyncIterator, TYPE_CHECKING

if TYPE_CHECKING:
    from src.core.dto import Asset, Ticker, Order
    from src.core.entities import Coin, Exchange


class IExchange(Protocol):
    async def buy(self, asset: "Asset") -> "Order": ...
    async def sell(self, asset: "Asset") -> "Order": ...
    async def transfer(self, asset: "Asset", destination: "IExchange") -> "Order": ...
    
    def subscribe_balance(self, coins: set["Coin"]) -> AsyncIterator["Asset"]: ...
    def subscribe_price(self, coins: set["Coin"]) -> AsyncIterator["Ticker"]: ...
    
    async def launch(self, tg: asyncio.TaskGroup) -> None: ...
    async def stop(self) -> None: ...
    
    async def get_withdrawal_fee(self, coin: "Coin") -> Decimal: ...
    async def get_available_coins(self) -> list["Coin"]: ...
    async def get_initial_price(self, coin: "Coin") -> Decimal: ...
    async def get_trading_fee(self, base: "Coin", quote: "Coin") -> Decimal: ...
    
    async def get_deposit_address(self, coin: "Coin") -> str: ...
    
    def get_instance(self) -> Exchange: ...